package fr.dynamx.common.slopes;

import com.jme3.math.Vector3f;
import fr.aym.acslib.services.impl.thrload.DynamXThreadedModLoader;
import fr.dynamx.api.physics.terrain.ITerrainElement;
import fr.dynamx.utils.DynamXConstants;
import fr.dynamx.utils.VerticalChunkPos;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;

import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/**
 * Renders the live preview of slopes generated by the {@code ItemSlopes}.
 *
 * <p>TODO port:1.20.1 - The original implementation uses {@code RenderWorldLastEvent}, {@code GlStateManager}
 * legacy OpenGL fixed pipeline, {@code ClientDebugSystem} client helpers, and many obj-loader/client classes
 * that have not been ported yet (Phase 7/8). The class skeleton (including the static slopes preview
 * terrain loader registration) is preserved so other modules can reference it; rendering body is stubbed.
 */
@Mod.EventBusSubscriber(modid = DynamXConstants.ID, value = Dist.CLIENT)
public class SlopePreviewer {
    private static final ExecutorService POOL = Executors.newSingleThreadExecutor(new DynamXThreadedModLoader.DefaultThreadFactory("SlopesPreviewer"));

    private static Map<VerticalChunkPos, List<ITerrainElement.IPersistentTerrainElement>> slopeCache;
    private static Vector3f cacheP1, cacheP2;
    private static List<Vector3f> cachePoints;
    private static int cacheVersion = -1;

    private static final SlopesPreviewTerrainLoader slopesPreviewer = new SlopesPreviewTerrainLoader();

    static {
        // TODO port:1.20.1 - DynamXTerrainApi.addCustomTerrainLoader hook (Phase 6); preserves the registration call site.
        // DynamXTerrainApi.addCustomTerrainLoader(slopesPreviewer);
    }

    @SubscribeEvent
    public static void worldRender(Object event) {
        // TODO port:1.20.1 - re-implement against RenderLevelStageEvent + modern Tesselator pipeline once client port lands.
    }
}
